/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as DigitalSignRouteImport } from './routes/digital-sign'
import { Route as FillFormsRouteImport } from './routes/fill-forms'
import { Route as ImagesToPdfRouteImport } from './routes/images-to-pdf'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as OrganizeRouteImport } from './routes/organize'
import { Route as PageNumbersRouteImport } from './routes/page-numbers'
import { Route as PdfToImagesRouteImport } from './routes/pdf-to-images'
import { Route as ProtectRouteImport } from './routes/protect'
import { Route as SignRouteImport } from './routes/sign'
import { Route as SplitRouteImport } from './routes/split'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as WatermarkRouteImport } from './routes/watermark'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalSignRoute = DigitalSignRouteImport.update({
  id: '/digital-sign',
  path: '/digital-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const FillFormsRoute = FillFormsRouteImport.update({
  id: '/fill-forms',
  path: '/fill-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesToPdfRoute = ImagesToPdfRouteImport.update({
  id: '/images-to-pdf',
  path: '/images-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizeRoute = OrganizeRouteImport.update({
  id: '/organize',
  path: '/organize',
  getParentRoute: () => rootRouteImport,
} as any)
const PageNumbersRoute = PageNumbersRouteImport.update({
  id: '/page-numbers',
  path: '/page-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToImagesRoute = PdfToImagesRouteImport.update({
  id: '/pdf-to-images',
  path: '/pdf-to-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectRoute = ProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const WatermarkRoute = WatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/digital-sign': typeof DigitalSignRoute
  '/fill-forms': typeof FillFormsRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/merge': typeof MergeRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/protect': typeof ProtectRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/unlock': typeof UnlockRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/digital-sign': typeof DigitalSignRoute
  '/fill-forms': typeof FillFormsRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/merge': typeof MergeRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/protect': typeof ProtectRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/unlock': typeof UnlockRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compress': typeof CompressRoute
  '/digital-sign': typeof DigitalSignRoute
  '/fill-forms': typeof FillFormsRoute
  '/images-to-pdf': typeof ImagesToPdfRoute
  '/merge': typeof MergeRoute
  '/organize': typeof OrganizeRoute
  '/page-numbers': typeof PageNumbersRoute
  '/pdf-to-images': typeof PdfToImagesRoute
  '/protect': typeof ProtectRoute
  '/sign': typeof SignRoute
  '/split': typeof SplitRoute
  '/unlock': typeof UnlockRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compress'
    | '/digital-sign'
    | '/fill-forms'
    | '/images-to-pdf'
    | '/merge'
    | '/organize'
    | '/page-numbers'
    | '/pdf-to-images'
    | '/protect'
    | '/sign'
    | '/split'
    | '/unlock'
    | '/watermark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compress'
    | '/digital-sign'
    | '/fill-forms'
    | '/images-to-pdf'
    | '/merge'
    | '/organize'
    | '/page-numbers'
    | '/pdf-to-images'
    | '/protect'
    | '/sign'
    | '/split'
    | '/unlock'
    | '/watermark'
  id:
    | '__root__'
    | '/'
    | '/compress'
    | '/digital-sign'
    | '/fill-forms'
    | '/images-to-pdf'
    | '/merge'
    | '/organize'
    | '/page-numbers'
    | '/pdf-to-images'
    | '/protect'
    | '/sign'
    | '/split'
    | '/unlock'
    | '/watermark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompressRoute: typeof CompressRoute
  DigitalSignRoute: typeof DigitalSignRoute
  FillFormsRoute: typeof FillFormsRoute
  ImagesToPdfRoute: typeof ImagesToPdfRoute
  MergeRoute: typeof MergeRoute
  OrganizeRoute: typeof OrganizeRoute
  PageNumbersRoute: typeof PageNumbersRoute
  PdfToImagesRoute: typeof PdfToImagesRoute
  ProtectRoute: typeof ProtectRoute
  SignRoute: typeof SignRoute
  SplitRoute: typeof SplitRoute
  UnlockRoute: typeof UnlockRoute
  WatermarkRoute: typeof WatermarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-sign': {
      id: '/digital-sign'
      path: '/digital-sign'
      fullPath: '/digital-sign'
      preLoaderRoute: typeof DigitalSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fill-forms': {
      id: '/fill-forms'
      path: '/fill-forms'
      fullPath: '/fill-forms'
      preLoaderRoute: typeof FillFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images-to-pdf': {
      id: '/images-to-pdf'
      path: '/images-to-pdf'
      fullPath: '/images-to-pdf'
      preLoaderRoute: typeof ImagesToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize': {
      id: '/organize'
      path: '/organize'
      fullPath: '/organize'
      preLoaderRoute: typeof OrganizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-numbers': {
      id: '/page-numbers'
      path: '/page-numbers'
      fullPath: '/page-numbers'
      preLoaderRoute: typeof PageNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-images': {
      id: '/pdf-to-images'
      path: '/pdf-to-images'
      fullPath: '/pdf-to-images'
      preLoaderRoute: typeof PdfToImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect': {
      id: '/protect'
      path: '/protect'
      fullPath: '/protect'
      preLoaderRoute: typeof ProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watermark': {
      id: '/watermark'
      path: '/watermark'
      fullPath: '/watermark'
      preLoaderRoute: typeof WatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompressRoute: CompressRoute,
  DigitalSignRoute: DigitalSignRoute,
  FillFormsRoute: FillFormsRoute,
  ImagesToPdfRoute: ImagesToPdfRoute,
  MergeRoute: MergeRoute,
  OrganizeRoute: OrganizeRoute,
  PageNumbersRoute: PageNumbersRoute,
  PdfToImagesRoute: PdfToImagesRoute,
  ProtectRoute: ProtectRoute,
  SignRoute: SignRoute,
  SplitRoute: SplitRoute,
  UnlockRoute: UnlockRoute,
  WatermarkRoute: WatermarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
